In [3]:
import Algorithmia

 

input = {
  "image": "data://.my/a_peace_treaty_2018/16.jpg",
  "model": "small"
}
client = Algorithmia.client('simPUEy64SQzKk6xDm/syOrBemZ1')
algo = client.algo('algorithmiahq/DeepFashion/1.2.2')
data= algo.pipe(input)



In [11]:
import Algorithmia
import os
import csv

fashion_dir = "a_peace_treaty_2018"
data_set=[]
client = Algorithmia.client('simPUEy64SQzKk6xDm/syOrBemZ1')
dir = client.dir("data://.my/" + fashion_dir)


for file in dir.files():
    input = {
        "image": "data://" + file.path,
        "model": "small"
    }

    algo = client.algo('algorithmiahq/DeepFashion/1.2.2')
    data = algo.pipe(input)
    for a in data.result['articles']:
        el= dict(
            img_url = file.path,
            article_name = a["article_name"],
            confidence = a["confidence"],
            bounding_box = a["bounding_box"],
            output = data.result["output"]
        )
        data_set.append(el)






In [12]:
data_set

[{'article_name': 'jewelry',
  'bounding_box': {'x0': 447, 'x1': 470, 'y0': 160, 'y1': 199},
  'confidence': 0.5385585427284241,
  'img_url': '.my/a_peace_treaty_2018/3.jpg',
  'output': 'data://.algo/algorithmiahq/deepFashion/temp/1f243ac7-a216-4b35-ba6c-990a918d79d3.png'},
 {'article_name': 'casual dress',
  'bounding_box': {'x0': 133, 'x1': 644, 'y0': 290, 'y1': 1102},
  'confidence': 0.8648462295532227,
  'img_url': '.my/a_peace_treaty_2018/3.jpg',
  'output': 'data://.algo/algorithmiahq/deepFashion/temp/1f243ac7-a216-4b35-ba6c-990a918d79d3.png'},
 {'article_name': 'jewelry',
  'bounding_box': {'x0': 299, 'x1': 328, 'y0': 148, 'y1': 194},
  'confidence': 0.5107566714286804,
  'img_url': '.my/a_peace_treaty_2018/8.jpg',
  'output': 'data://.algo/algorithmiahq/deepFashion/temp/5e2d788a-cbf4-4931-bc8f-64aca159b717.png'},
 {'article_name': 'jewelry',
  'bounding_box': {'x0': 420, 'x1': 451, 'y0': 155, 'y1': 207},
  'confidence': 0.6280559301376343,
  'img_url': '.my/a_peace_treaty_2018

In [13]:
SAVEFILE = "data/" + fashion_dir + ".csv"

with open(SAVEFILE, "w", newline="") as file:
    columns = ["img_url","article_name", "confidence", "bounding_box",  "output" ]
    writer = csv.DictWriter(file, fieldnames=columns)
    writer.writeheader()

    writer.writerows(data_set)

In [15]:
data.result['articles'][0]['bounding_box']

{'x0': 280, 'x1': 387, 'y0': 779, 'y1': 937}

In [18]:
data.result['articles'][0]['confidence']


'data://.algo/algorithmiahq/deepFashion/temp/e9122be4-4bcb-4e78-a249-67d37644a45a.png'

In [ ]:
if client.file(data.result['output']).exists() is True:
    localfile = client.file(data.result['output']).getFile()



In [154]:
import matplotlib.pyplot as plt

from sklearn.feature_extraction.image import grid_to_graph
from sklearn.cluster import AgglomerativeClustering

import scipy as sp

from PIL import Image
import numpy as np

 
def show(a):
    img = Image.fromarray(a, 'RGB')
    img.save('my.png')
    img.show()



from sklearn import cluster, datasets
iris = datasets.load_iris()
X_iris = iris.data
y_iris = iris.target

k_means = cluster.KMeans(n_clusters=3)
k_means.fit(X_iris) 

print(k_means.labels_[::10])

print(y_iris[::10])


try:
   face = sp.face(gray=True)
except AttributeError:
   from scipy import misc
   face = misc.face(gray=True)

X = face.reshape((-1, 1)) # We need an (n_sample, n_feature) array
k_means = cluster.KMeans(n_clusters=5, n_init=1)
k_means.fit(X) 

values = k_means.cluster_centers_.squeeze()
labels = k_means.labels_
face_compressed = np.choose(labels, values)
face_compressed.shape = face.shape



# #############################################################################
# Generate data
try:  # SciPy >= 0.16 have face in misc
    from scipy.misc import face
    face = face(gray=True)
except ImportError:
    face = sp.face(gray=True)

   
    
# Resize it to 10% of the original size to speed up the processing
face = sp.misc.imresize(face, 0.10) / 255.
 
X = np.reshape(face, (-1, 1))

# #############################################################################
# Define the structure A of the data. Pixels connected to their neighbors.
connectivity = grid_to_graph(*face.shape)


X.imag


# #############################################################################

[1 1 1 1 1 0 0 0 0 0 2 2 2 2 2]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:60: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

array([[0.46666667],
       [0.40784314],
       [0.38039216],
       ...,
       [0.5372549 ],
       [0.54509804],
       [0.55686275]])

In [1]:
type(face)

NameError: name 'face' is not defined